services:
  web:
    image: javimosch/indep-bauges-web:latest
    volumes:
      - ./:/app
    expose:
      - 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped