services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indep-bauges-web
    image: javimosch/indep-bauges-web:1.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Admin authentication - override these in production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-123456}
      - JWT_SECRET=${JWT_SECRET:-indep-bauges-secret-key}
    restart: unless-stopped
