services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indep-bauges-web
    image: javimosch/indep-bauges-web:1.0
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./src:/app/src
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped